---
title: "HW2"
author: "Jiaying Shi"
date: "10/3/2019"
output: html_document
---

```{r setup, include=FALSE}
require(rgdal)
require(leaflet)
require(leaflet.extras)
require(dplyr)
require(readxl)
require(stringr)
```

# Seattle Budiling Map with Permit Type

```{r}
#Load Data
permit <- read.csv("Building_Permit.csv")

pal <- colorFactor(c("#E69F00", "#1A9850"), c("Non-Residential", "Residential"))

#Map
leaflet() %>%
  addProviderTiles("OpenStreetMap.DE") %>%
  #add a layer of points
  addCircleMarkers(data = permit, 
                   lng = ~Longitude, 
                   lat = ~Latitude, 
                   radius = 1,
                   color = ~pal(PermitClassMapped),
                  clusterOptions = markerClusterOptions()) %>%
  #add legend
  addLegend(position = "topright", 
            pal = pal, 
            values = permit$PermitClassMapped, 
            title = "Permit Type")
```

# Seattle Budiling Map with Permit Class

```{r}
type <- unique(permit$PermitClass)

pal1 <-colorFactor(palette = "RdYlBu", domain = type )

#Map
leaflet() %>%
  addProviderTiles("OpenStreetMap.HOT", group = "HOT") %>%
  addProviderTiles("OpenTopoMap", group = "Topo") %>%
  addProviderTiles("Stamen.TonerLite", group = "Toner Lite") %>%
  #add a layer of points
  addCircleMarkers(data = permit, 
                   lng = ~Longitude, 
                   lat = ~Latitude, 
                   radius = 1,
                   color = ~pal1(type)) %>%
  #add legend
  addLegend(position = "bottomright", 
            pal = pal1, 
            values = permit$PermitClass, 
            title = "Permit Class") %>%
  #add layers control
  addLayersControl(
    baseGroups = c("HOT", "Topo", "Toner Lite"),
    options = layersControlOptions(collapsed = FALSE)
  )

```

# Greater Downtown Alleys in Seattle

```{r}
#Load Data
alley <- readOGR("Greater_Downtown_Alleys.geojson")

#Map
leaflet(data = alley) %>%
  addProviderTiles("OpenStreetMap.DE") %>%
  #add a layer of lines
  addPolylines(color = "blue")
```

Educational Services Districts in Washington State
```{r}
#Load Data
esd <-readOGR("/Users/jiayingshi/Rshiny/hw2_jiaying2/ESD Boundaries.geojson")

#Polygon Map
leaflet(esd) %>%
  addProviderTiles("Hydda.Full") %>%
  addPolygons()

```

